import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from './ReactQueryProvider';
import { FavoriteMoviesProvider } from "@/components/context/FavoriteMoviesContext";
import { ThemeProvider } from "@/context/ThemeContext";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Movie Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <FavoriteMoviesProvider>
            <div className={`flex flex-col min-h-screen `}>
              <Navbar />
              <div className="flex flex-grow" >
                <ReactQueryProvider>{children}</ReactQueryProvider>
              </div>
              <Footer />
            </div>
          </FavoriteMoviesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
